# Generated by Django 4.2.20 on 2025-04-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
