# Generated by Django 4.2.20 on 2025-04-21 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin_territorial', 'Administrador Territorial'), ('company_small', 'Empresa Pequeña'), ('company_large', 'Empresa Grande'), ('environmental_intermediary', 'Intermediario Ambiental')], default='admin_territorial', max_length=30),
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_territory', models.BooleanField(default=False, help_text='¿Es un riesgo general del territorio?')),
                ('name', models.CharField(help_text='Nombre o título del riesgo', max_length=200)),
                ('residual', models.TextField(help_text='Elemento residual del riesgo que no se puede mitigar')),
                ('financial_impact', models.DecimalField(decimal_places=2, help_text='Impacto en las cuentas financieras', max_digits=12, verbose_name='Impacto financiero')),
                ('csv_file', models.FileField(blank=True, help_text='Carga un CSV con detalles adicionales', upload_to='risks_csv/')),
                ('gpt_link', models.URLField(blank=True, help_text='Enlace a tu modelo GPT personalizado para análisis ágil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(help_text='Usuario que reporta este riesgo', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
