# Generated by Django 4.2.20 on 2025-04-22 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_profile_role_risk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResilienceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del indicador', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional')),
                ('unit', models.CharField(help_text='Unidad de medida (ej: hectáreas, %)', max_length=50)),
                ('baseline', models.FloatField(help_text='Línea base del indicador')),
                ('target', models.FloatField(help_text='Meta esperada')),
                ('year_target', models.PositiveIntegerField(help_text='Año meta')),
                ('risk_focus', models.CharField(help_text='Riesgo principal al que responde', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
