# Generated by Django 4.2.20 on 2025-04-22 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_resilienceindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('indicator', models.CharField(help_text='Indicador objetivo', max_length=100)),
                ('status', models.CharField(choices=[('formulation', 'En Formulación'), ('active', 'Activo')], default='formulation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
