# Generated by Django 4.2.20 on 2025-04-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del intermediario'),
        ),
        migrations.AddField(
            model_name='profile',
            name='projects_done',
            field=models.PositiveIntegerField(default=0, help_text='Número de proyectos realizados'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0, help_text='Puntuación promedio'),
        ),
    ]
