# Generated by Django 4.2.20 on 2025-04-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_description_profile_projects_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('platform_admin', 'Administrador de Plataforma'), ('admin_territorial', 'Administrador Territorial'), ('company_small', 'Empresa Pequeña'), ('company_large', 'Empresa Grande'), ('environmental_intermediary', 'Intermediario Ambiental')], default='admin_territorial', max_length=30),
        ),
    ]
